### ISSUE TITLE
Separate NuGet for each framework

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#101]
Some developers would like to minimize their libraries.
Today NuGet doesn't download only the relevant targets, but rather downloads the whole nuget package.
Proposal to have Theraot.Core.NET20 .. Theraot.Core.NET47, Theraot.Core.NETStandard1.0.. and so on.

Related to: https://github.com/ViacheslavMezentsev/symbcs/issues/2

**Comment by theraot** [comment]
Would this not mess up with nuget dependencies? I mean, if there is a nuget that uses Theraot.Core and another that uses Theraot.Core.Net20 and I want to use them both in my project... now my client will download both Nugets. Hopefully that does not introduce futher conflicts in runtime (would have to experiment to make sure), however I would rather not follow this route.

If they are deploying and EXE, I guess it does not matter much what they use...

Sadly everybody will want a different subset...

If I were to follow the approach of splitting by target framework, there is some room to optimize for each one at expense of ease of use (if I want to have multiple targets, I need to reference a different package for each one).

Another idea is to split by functionality. In theory Linq+Expressions and Task+Threading are separable, although, in practice some parts of the code are used by both sides making the cut less clear.

It is there where I start to consider to have a common library that is used by the others... but then it is three libraries instead of one, and the argument of "a single small library" comes back to bite again.

---

I could imagine a tool that would build only the parts of the library that are used, and merge them into the EXE, however, that is easier said than done.

**Comment by NN---** [comment]
IMO the only real problem is the NuGet that downloads more than required :)
Yeah, most people just want LINQ and that's all but in fact they obviously want more.
