### ISSUE TITLE
Bug of StringHelper.Append(string, string[])

### ISSUE THREAD

**Issue by CreateAndInject** [theraot/Theraot#172]
https://github.com/theraot/Theraot/blob/c67d4fb1aba7c1029a793964fee110a8b2e6801f/Framework.Core/Theraot/Core/StringHelper.cs#L22-L25

string result = "a".Append("b", "c", "d", "e"); // result: "aSystem.String[]"

**Comment by NN---** [comment]
Since it is a helper method and defined only for older .NET, probably it could be simply removed.
Is there any real use-case for it ?

**Comment by NN---** [comment]
IMO the best solution is to remove this method as implementing it efficiently is not so easy.
For instance string.Concat(IEnumerable) presents only since .NET 4.0 and using string.Concat(string[]) means allocating a new array and copying the older one.
If you look in the string.Concat implementation it has various optimization techniques:
https://source.dot.net/#System.Private.CoreLib/String.Manipulation.cs,193

The simplest way for now is to use StringBuilder.
