### ISSUE TITLE
Support UWP by adding "uap" target

### ISSUE THREAD

**Issue by dahall** [theraot/Theraot#23]
Are you open to adding a `uap` to `TargetFrameworks` in your builds so as to directly support UWP projects adding your package? If so, I'm happy to submit a PR.

**Comment by dahall** [comment]
Another question: Your projects are all setup using the older .csproj format. It is a lot simpler to use the new SDK format for multi-targeting and would simplify adding support for UWP. I would be willing to help with the upgrade if you're willing. It does require Visual Studio 2017.

**Comment by theraot** [comment]
Will try, I have barely look into it. Using the format I use has not been a problem. Yes, I am using Visual Studio 2017.

**Comment by theraot** [comment]
@dahall It seems to be I get stuck with Microsoft.NET.Sdk.BeforeCommon.targets

There are a few types I do not backport because they are in WindowsBase. Because those types exist there, I added WindowsBase as a reference... however I can't do that, or at least not without getting rid of Microsoft.NET.Sdk.BeforeCommon.targets.

I did try getting rid of Microsoft.NET.Sdk.BeforeCommon.targets but have been unable to get it to work. This suggest to me that if it is possible, it is probably a big hassle and most developer won't do it. For me it is trivial to just backport these types on the targets that don't have it and ignore WindowsBase (after all, WindowsBase is not available for .NET 2.0, and thus I have backports already made. This means that anybody using WindowsBase will now have a conflict with my types.

The alternative is to remove these types, do not backport them at all. Which sucks, because, as I said, WindowsBase is not available for .NET 2.0.

I had a look at apisof.net and the problematic types get decent use. Sadly that does not tell me how much of it is from WindowsBase. I am probably blowing this out of proportion, after all, if there is code in question that is barely used... it is mine.

I also had a look at dahall/Vanara (hey, I tell you theraot/theraot has Task, did you try them?), and you use INotifyPropertyChanged which is among the problematic types. Conspicously you skip .NET 3.0, when WindowsBase was added, is this a problem for you too?

Anyway, I will be dropping WindowsBase and put my own backports in. This will be version 3. Will see how AppVeyor like the changes.

It is also sad that this gets me stuck with references to System.Data, System.Drawing, and System.Xml, that I do not need and do not intent on supporting... well, I guess I have to at least consider it now.

**Comment by theraot** [comment]
@dahall I have pushed a yet to be tested version to the branch Develop_v3. If you can, I would like you to have a look at the project.

That version builds on .NET 2.0 to 4.7, .NET Core 1.0 to 2.1 and .NET Standard 1.0 to 1.6. Which what I managed to get working in Visual Studio 2017.

I do not know if that covers "uap", for what I see in https://docs.microsoft.com/en-us/dotnet/standard/frameworks "uap" is a different target, but I have not being able to make it work. If you can create/modify the project file appropriately, I'd appreciate it.

I did also try targets netcore45 and netcore50. It is my impression that netcore50 is equivalent to uap, and is worse than .net standard 1.0... which might be a problem.

I did also try installing MSBuildSdkExtras but it says that my project is not compatible.

---

As I said, this is yet to be tested... I do not expect this to work well, I haven't double checked the packages for .NET Standard to make sure I have not introduced a conflict, which means I probably have introduced a conflict.

**Comment by theraot** [comment]
@dahall I have managed to build for all .NET Standard versions up to .NET Standard 1.6. That means that you will be able to get uap10.0 via .NET Standard 1.4 and 10.0.16299 on .NET Standard 1.6. That will be on v3. I will add .NET Standard 2.0 later. A lot of testing still required.

**Comment by theraot** [comment]
@dahall Can you try 3.0.0-beta?

There some known issues, however, what I want to know is whatever or not you can use it from uap, which is what you asked for.
