### ISSUE TITLE
Task.Delay and Task.Run in .NET 4.0

### ISSUE THREAD

**Issue by dahall** [theraot/Theraot#24]
Any ideas on how to get the functionality of Task.Delay and Task.Run in .NET 4.0? Your library works for .NET 2.0 and 3.5, but not 4.0.

**Comment by theraot** [comment]
I cannot modify Task in .NET 4.0 and .NET 4.5 because it is included in the BCL. This is why a TaskEx class is provided. You will find the missing APIs there.

This is similar to what Microsoft did with the TPL.

For convenience there is a TaskEx for .NET 2.0, 3.0 and 3.5 that expose the same APIs. That is, in .NET 4.0 and 4.5 TaskEx is a workaround, and in .NET 2.0, 3.0 and 3.5 it is a thing wrapper, allowing you to use TaskEx for all versions of .NET Framwork.

**Comment by dahall** [comment]
That works well. Thank you.

**Comment by NN---** [comment]
Shouldn't you just use .NET Framework implementation for the new frameworks instead of own like EnumHelper does ?
