### ISSUE TITLE
Missing several API

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#28]
Please take a look here: https://github.com/rsdn/CodeJam/tree/master/CodeJam.Main/Targeting

Several APIs are missing in Theraot library such as:

```
System.ComponentModel.DataAnnotations.DisplayAttribute
System.Reflection.CustomAttributeExtensions
System.Runtime.Versioning.TargetFrameworkAttribute
...
```

As well ReadOnlyCollection in .NET 3.5 and .NET 4.0 doesn't implement IReadOnlyList as it does in .NET 4.5.
Same relevant to Dictionary class.

To preserve the same behavior you have to use some workaround such as:  [ReadOnlyCollectionWithReadOnly](https://github.com/rsdn/CodeJam/tree/222b1684be62251991b536ec06bdd0187e087b29/CodeJam.Main/Targeting/NET40/ReadOnlyCollectionWithReadOnly.cs) or [ReadOnlyCollectionWithReadOnly](https://github.com/rsdn/CodeJam/tree/222b1684be62251991b536ec06bdd0187e087b29/CodeJam.Main/Targeting/NET40/DictionaryWithReadOnly.cs) in [CodeJam](https://github.com/rsdn/CodeJam/).

I would like to use this library when all necessary classes will be backported.

**Comment by theraot** [comment]
Adding those should be no problem.

I have something similar to ReadOnlyCollectionWithReadOnly called ExtendedReadOnlyList, I can make an ExtendedReadOnlyDictionary.

**Comment by NN---** [comment]
Great.
I find this naming more confusing than CodeJam one cause you don't really extend functionality but just add an interface.

**Comment by theraot** [comment]
From the linked repository...

These are already in the library:
- Action.cs
- Func.cs
- IStructuralComparable.cs
- IStructuralEquatable.cs
- Tuple.cs
- Volatile.cs
- TupleElementNamesAttribute.cs
- TupleExtensions.cs
- ValueTuple.cs
- CustomAttributeExtensions.cs (from your pull request)
- IReadOnlyCollection.cs
- IReadOnlyDictionary.cs
- IReadOnlyList.cs

These are from System.ComponentModel (which I am not providing):

- DisplayAttribute.cs
- LocalizableString.cs

There will be equivalents of:
- DictionaryWithReadOnly.cs; will add ExtendedDictionary modified to fit this. See also NullAwareDictionary
- ListWithReadOnly.cs; will modify ExtendedList. See also EnumerationList.
- ReadOnlyCollectionWithReadOnly.cs: ExtendedReadOnlyList<T>

Others:
- EnumTargeting.cs: see Theraot.Core.EnumHelper
- StringTargeting.cs: see Theraot.Core.StringHelper
- EnumerableTargeting.cs: see note
- TargetFrameworkAttribute.cs: added

Note: I had removed the workaround for Zip by accident in an attempt to keep the size of library in check. Did not notice, because, to be honest, I did not have test for it. I have added it back, you will find it in Theraot.Collections.Extensions.Zip.

About naming: Given that I will be releasing v3, I will be renaming these from ExtendedSomething to SomethingEx. That should also make them easier to find. They were originally doing more, however, most of it was cut out for library size.

**Comment by NN---** [comment]
I can make PR with DisplayAttribute.cs and 
LocalizableString.cs if you are willing to add them to the library.

What is the problem with size ?
I don't think anyone bothers today with +-few MBs.

**Comment by theraot** [comment]
I had another look at them. I noticed that LocalizableString is not exposed.

It mean that I will not be backporting Microsoft.Azure.Management.Websites.dll which I do not know if it is possible, do not think makes sense to have in the same dll, and do not want to do.

With that in mind, I am ok with adding DisplayAttribute and commit to add all the types from System.ComponentModel.Annotations.

---

Size? I take it as a discipline of not adding stuff that is not helping to backport something. With that said, I have been told to keep the size down by a couple people.

Sometimes I develop code for a prototype and then decide on a different approach, then I have code that is not needed... and I did over correct and remove stuff that was actually a workaround for Zip.

**Comment by NN---** [comment]
Correct, LocalizableString is internal, DisplayAttribute is public class.

**Comment by theraot** [comment]
I believe I have all the types already covered in source.

**Comment by NN---** [comment]
If you could release nuget package as prerelease version 3.0-beta , I will test it and tell you whether anything else is missing or not working as expected.

**Comment by theraot** [comment]
@NN--- sure, I'll push a prerelease later today. I'll reopen meanwhile.

**Comment by theraot** [comment]
@NN--- publishing nuget as I write.

**Comment by NN---** [comment]
Why System.ValueTuple is not defined for .NET 4.0 ?
[System.Value](https://www.nuget.org/packages/System.ValueTuple/) NuGet doesn't support 4.0.

**Comment by theraot** [comment]
@NN--- Aside from #39 is there something else missing?

**Comment by theraot** [comment]
@NN--- I have actually decided on that, it will be System.Linq.EnumerableTheraotExtensions

Yes, I know it is verbose, however:

1. You should not be referencing it directly, instead by the extension method only
2. It will not collide now or ever with a Microsoft type or any other library (unless their developers intentionally decide to, or are taking it from me).

**Comment by NN---** [comment]
I use "using Theraot.Collections;" , is it correct ?
Right now there are no problems with v3.
All tests pass.

**Comment by theraot** [comment]
@NN--- yes, that is how it is right now. Opened #40 for the extension methods, I'm closing this.

**Comment by NN---** [comment]
I have some tests failing, possibly due to Theraot. Will take a look.

**Comment by NN---** [comment]
#42
