### ISSUE TITLE
T4 for code generation

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#37]
Wouldn't it be better to use T4 or other tool for code generation for repetitive code such as Func, Action, Tuple ?

**Comment by theraot** [comment]
There is little gain from using T4 for these because:

1. These types will not be changing
2. We would store both the T4 and the generated code in the repository

I have used T4 sparsely. Although I added Func and Action before I learned to used it, I would probably have used it for those... However, once they are done, why would I add a T4?

T4 also has some drawbacks on maintainability:

1. It has worse code analysis support
2. It requires to maintain the relationship between T4 file and generated file in the project file (or else, we may have a T4 that generates to a different or does not generate at all), which is a problem when moving code or renaming files

Because of these, I will consider to to remove a T4 file before I consider repairing it
